services:
  fcp-find-ai-frontend:
    build:
      context: .
      target: production
    image: fcp-find-ai-frontend
    container_name: fcp-find-ai-frontend
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-find-ai-frontend-local
