- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: FARMING_FUNDING_API_URI
  value: https://find-ai-data-gathering.azurewebsites.net/api
- key: FARMING_FUNDING_API_KEY
  value: "{{servicename}}-FARMING-FUNDING-API-KEY"