- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: COOKIE_PASSWORD
  value: "{{servicename}}-COOKIE-PASSWORD"
  type: "keyvault"
- key: AUTH_USER
  value: "{{servicename}}-AUTH-USER"
  type: "keyvault"
- key: AUTH_PASSWORD
  value: "{{servicename}}-AUTH-PASSWORD"
  type: "keyvault"
- key: AUTH_VERIFICATION
  value: "{{servicename}}-AUTH-VERIFICATION"
  type: "keyvault"
- key: REDIS_HOST
  value: "{{servicename}}-REDIS-HOST"
  type: "keyvault"
- key: REDIS_PASSWORD
  value: "{{servicename}}-REDIS-PASSWORD"
  type: "keyvault"
- key: REDIS_PORT
  value: "{{servicename}}-REDIS-PORT"
  type: "keyvault"
- key: AZURE_AISEARCH_ENDPOINT
  value: "{{servicename}}-AZURE-AISEARCH-ENDPOINT"
  type: "keyvault"
- key: AZURE_AISEARCH_KEY
  value: "{{servicename}}-AZURE-AISEARCH-KEY"
  type: "keyvault"
- key: AZURE_SEARCH_INDEX_NAME
  value: "{{servicename}}-AZURE-SEARCH-INDEX-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_API_INSTANCE_NAME
  value: "{{servicename}}-AZURE-OPENAI-API-INSTANCE-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_API_ENDPOINT
  value: "{{servicename}}-AZURE-OPENAI-API-ENDPOINT"
  type: "keyvault"
- key: AZURE_OPENAI_API_KEY
  value: "{{servicename}}-AZURE-OPENAI-API-KEY"
  type: "keyvault"
- key: AZURE_OPENAI_API_EMBEDDING_DEPLOYMENT_NAME
  value: "{{servicename}}-AZURE-OPENAI-API-EMBEDDING-DEPLOYMENT-NAME"
  type: "keyvault"
- key: AZURE_OPENAI_API_MODEL_NAME
  value: "{{servicename}}-AZURE-OPENAI-API-MODEL-NAME"
  type: "keyvault"
- key: GOOGLE_TAG_MANAGER_KEY
  value: "G-NF25VDMQQX"
