{{- include "adp-helm-library.deployment" (list . "fcp-find-ai-frontend.deployment") -}}
{{- define "fcp-find-ai-frontend.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "fcp-find-ai-frontend.container") }}
{{- end -}}
